### ISSUE TITLE
pyproject.toml PEP 518 Compliance

### ISSUE THREAD

**Issue by harens** [Ciphey/CipheyDists#8]
I am currently trying to write a homebrew formula for [Ciphey/Ciphey](https://github.com/Ciphey/Ciphey), which has CipheyDists as a dependency. When I try to build it from the source distribution on the  [PyPi download page](https://pypi.org/project/cipheydists/#files), I run into the following errors that do not allow it to build:
```
pip._internal.exceptions.InstallationError: file:///private/tmp/ciphey--cipheydists-20200806-89313-q77e67/cipheydists-0.3.18 has a pyproject.toml file that does not comply with PEP 518: it has a 'build-system' table but not 'build-system.requires' which is mandatory in the table
```
```
ERROR: file:///private/tmp/ciphey--cipheydists-20200806-89313-q77e67/cipheydists-0.3.18 has a pyproject.toml file that does not comply with PEP 518: it has a 'build-system' table but not 'build-system.requires' which is mandatory in the table
```
<details><summary>Full Terminal Output</summary>
<p>

```
==> /usr/local/Cellar/ciphey/5.0.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ciphey--cipheydists-20200806-89313-q77e67/cipheydists-0.3.18
Using pip 20.2.1 from /usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-5_8_omui
Created temporary directory: /private/tmp/pip-req-tracker-69j6gngx
Initialized build tracking at /private/tmp/pip-req-tracker-69j6gngx
Created build tracker: /private/tmp/pip-req-tracker-69j6gngx
Entered build tracker: /private/tmp/pip-req-tracker-69j6gngx
Created temporary directory: /private/tmp/pip-install-xsg6cqft
Processing /private/tmp/ciphey--cipheydists-20200806-89313-q77e67/cipheydists-0.3.18
  Created temporary directory: /private/tmp/pip-req-build-vm5_q7l5
  Added file:///private/tmp/ciphey--cipheydists-20200806-89313-q77e67/cipheydists-0.3.18 to build tracker '/private/tmp/pip-req-tracker-69j6gngx'
ERROR: file:///private/tmp/ciphey--cipheydists-20200806-89313-q77e67/cipheydists-0.3.18 has a pyproject.toml file that does not comply with PEP 518: it has a 'build-system' table but not 'build-system.requires' which is mandatory in the table
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 324, in run
    requirement_set = resolver.resolve(
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 33, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 503, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "/usr/local/Cellar/ciphey/5.0.0/libexec/lib/python3.8/site-packages/pip/_internal/pyproject.py", line 147, in load_pyproject_toml
    raise InstallationError(
pip._internal.exceptions.InstallationError: file:///private/tmp/ciphey--cipheydists-20200806-89313-q77e67/cipheydists-0.3.18 has a pyproject.toml file that does not comply with PEP 518: it has a 'build-system' table but not 'build-system.requires' which is mandatory in the table
Removed file:///private/tmp/ciphey--cipheydists-20200806-89313-q77e67/cipheydists-0.3.18 from build tracker '/private/tmp/pip-req-tracker-69j6gngx'
Removed build tracker: '/private/tmp/pip-req-tracker-69j6gngx'
```
</p>
</details>

<details><summary>Configuration</summary>
<p>

```
HOMEBREW_VERSION: 2.4.9-264-ga9f5925
ORIGIN: https://github.com/Homebrew/brew
HEAD: a9f5925cdfcb3279b5e8ba2730747db9c1cac680
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 719f211fc1ba14a3ed32257262bd341564fe313b
Core tap last commit: 3 days ago
Core tap branch: ShallowBackup
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.CAAFfIMowi/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2
macOS: 10.15.6-x86_64
CLT: 1103.0.32.59
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```
</p>
</details>

<details><summary>Environment</summary>
<p>

```
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python@3.8/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.8/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python@3.8/bin:/usr/local/opt/poetry/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
</p>
</details>

**Comment by brandonskerritt** [comment]
Strange! We appear to have a build-system requires:

```
  41   │ [build-system]
  42   │ requires = ["poetry>=0.12"]
  43   │ build-backend = "poetry.masonry.api"
```

I'll explore this some more :)

**Comment by Cyclic3** [comment]
@harens Does that fix it for you?
